### ISSUE TITLE
Did you implement 'minibatch discrimination'?

### ISSUE THREAD

**Issue by Lucksong** [daixiangzi/ImprovedGan-pytorch#1]
Hello , thanks for your code.
I have briefly reviewed your code but I didn`t find the implementation of minibatch discrimination. Did you reproduce it?

**Comment by Lucksong** [comment]
'vbn' is the same

**Comment by daixiangzi** [comment]
oh,sorry.i only reproduce match feature section.i think you can try it,no very difficult



---Original---
